### ISSUE TITLE
build失败：Page "/[lang]/about" is missing "generateStaticParams()" so it cannot  be used with "output: export" config.

### ISSUE THREAD

**Issue by dooonabe** [huglemon/inwind-landing-page#4]
我本来想打个静态资源包放到nginx下用，就在nextconfig中加了output: export，结果报错了上面的错误，麻烦作者看看

**Comment by huglemon** [comment]
不好意思我刚看到。你这个output:export是直接导出所有的静态页面，但我这个用到了动态多语言，所以没办法这样导出。如果需要导出的话，需要你添加一下generateStaticParams这个方法，把所有语言作为参数列进去，让next知道[lang]都对应哪些语言。
