### ISSUE TITLE
去掉layout.js 里面的<ThemeProvider> 就能SSR，是不是可以优化一下ThemeProvider

### ISSUE THREAD

**Issue by my19940202** [huglemon/inwind-landing-page#8]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/e28b25ae-0476-4f62-9934-d86df82a515f">

SSR
<img width="956" alt="image" src="https://github.com/user-attachments/assets/1829dfa3-b957-402c-9b72-e1603adfa645">
CSR
![image](https://github.com/user-attachments/assets/3c100368-f881-4e20-8ac7-8cd620bd04ff)

**Comment by huglemon** [comment]
已改进，感谢反馈
